/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Damian
 */
public class RegistroEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public RegistroEstudiantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelData1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        errNombre = new javax.swing.JLabel();
        errApellido = new javax.swing.JLabel();
        errCedula = new javax.swing.JLabel();
        errCarrera = new javax.swing.JLabel();
        boxCarrera = new javax.swing.JComboBox<>();
        panelCRUD = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        panelData2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        spnCreditos = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        radPosgrado = new javax.swing.JRadioButton();
        radPregrado = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        errCreditos = new javax.swing.JLabel();
        errNivel = new javax.swing.JLabel();
        txtPromedio = new javax.swing.JTextField();
        errPromedio = new javax.swing.JLabel();
        panelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Gestion de Estudiante");

        panelData1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        panelData1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre :");
        panelData1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 20));

        jLabel3.setText("Apellido :");
        panelData1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, 20));

        jLabel4.setText("Cedula :");
        panelData1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 110, 80, 20));

        jLabel5.setText("Carrera :");
        panelData1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, 20));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        panelData1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 250, -1));

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        panelData1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 250, -1));
        panelData1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 250, -1));

        errNombre.setText("errNombre");
        panelData1.add(errNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 250, -1));

        errApellido.setText("errApellido");
        panelData1.add(errApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 250, -1));

        errCedula.setText("errCedula");
        panelData1.add(errCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 250, -1));

        errCarrera.setText("errCarrera");
        panelData1.add(errCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 250, -1));

        boxCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "ITIN", "AGRO", "BIO", " " }));
        panelData1.add(boxCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 250, -1));

        panelCRUD.setBorder(javax.swing.BorderFactory.createTitledBorder("CRUD"));
        panelCRUD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setText("Guardar");
        panelCRUD.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 90, 40));

        btnLimpiar.setText("Limpiar");
        panelCRUD.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 90, 40));

        btnActualizar.setText("Actualizar");
        panelCRUD.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 100, 40));

        btnEliminar.setText("Eliminar");
        panelCRUD.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 100, 40));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelCRUD.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 90, 40));

        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });
        panelCRUD.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 100, 40));

        panelData2.setBorder(javax.swing.BorderFactory.createTitledBorder("Perfil academico"));
        panelData2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Numero de Creditos :");
        panelData2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        panelData2.add(spnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 80, -1));

        jLabel11.setText("Nivel :");
        panelData2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 60, 20));

        buttonGroup1.add(radPosgrado);
        radPosgrado.setText("Posgrado");
        panelData2.add(radPosgrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        buttonGroup1.add(radPregrado);
        radPregrado.setText("Pegrado");
        radPregrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPregradoActionPerformed(evt);
            }
        });
        panelData2.add(radPregrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jLabel12.setText("Promedio :");
        panelData2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 20));

        errCreditos.setText("errCreditos");
        panelData2.add(errCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        errNivel.setText("errNivel");
        panelData2.add(errNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));
        panelData2.add(txtPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 80, -1));

        errPromedio.setText("errPromedio");
        panelData2.add(errPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 20));

        panelTable.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de datos"));

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Cedula", "Carrera", "Nº credito", "Promedio", "Nivel", "Becario", "Total"
            }
        ));
        jScrollPane1.setViewportView(tbDatos);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
        );

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(224, 224, 224))
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCRUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelHomeLayout.createSequentialGroup()
                                .addComponent(panelData1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelData2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelData1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(panelData2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTable, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void radPregradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPregradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radPregradoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefrescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxCarrera;
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnRefrescar;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JLabel errApellido;
    public javax.swing.JLabel errCarrera;
    public javax.swing.JLabel errCedula;
    public javax.swing.JLabel errCreditos;
    public javax.swing.JLabel errNivel;
    public javax.swing.JLabel errNombre;
    public javax.swing.JLabel errPromedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCRUD;
    private javax.swing.JPanel panelData1;
    private javax.swing.JPanel panelData2;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelTable;
    public javax.swing.JRadioButton radPosgrado;
    public javax.swing.JRadioButton radPregrado;
    public javax.swing.JSpinner spnCreditos;
    public javax.swing.JTable tbDatos;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPromedio;
    // End of variables declaration//GEN-END:variables
}
