/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import java.util.Scanner;
import javax.swing.SpinnerNumberModel;
public class IngresarVehiculo extends javax.swing.JFrame {
    static Scanner cin = new Scanner(System.in);
    public IngresarVehiculo() {
        initComponents();
        Group_RadBtn.add(radBtnAuto);
        Group_RadBtn.add(radBtnMoto);
        this.setBounds(400, 50, 465, 500);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group_RadBtn = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnPisos = new javax.swing.JSpinner();
        spnBloques = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        radBtnAuto = new javax.swing.JRadioButton();
        radBtnMoto = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        errorNombre = new javax.swing.JLabel();
        errorTipo = new javax.swing.JLabel();
        errorPlaca = new javax.swing.JLabel();
        errorFechaIngreso = new javax.swing.JLabel();
        errorHoraIngreso = new javax.swing.JLabel();
        errorTelefono = new javax.swing.JLabel();
        errorPiso = new javax.swing.JLabel();
        errorBloque = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("INGRESO DE DATOS"));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Nombre :  ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Num. Placa :  ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 90, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Hora Ingreso:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Teléfono :  ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 70, 20));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 170, -1));
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 180, -1));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 170, -1));

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 100, 40));

        btnGenerate.setText("GENERAR");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 100, 40));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Piso :  ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 90, 20));

        jLabel6.setText("Bloque :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 50, 20));

        spnPisos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 2, 1));
        jPanel1.add(spnPisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        spnBloques.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        jPanel1.add(spnBloques, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Tipo :  ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 80, 90, 20));

        radBtnAuto.setText("Auto");
        radBtnAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnAutoActionPerformed(evt);
            }
        });
        jPanel1.add(radBtnAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        radBtnMoto.setText("Moto");
        radBtnMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnMotoActionPerformed(evt);
            }
        });
        jPanel1.add(radBtnMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Fecha Ingreso :  ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 90, 20));

        errorNombre.setText("sdsdsd");
        jPanel1.add(errorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        errorTipo.setText("sdsdsd");
        jPanel1.add(errorTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        errorPlaca.setText("sdsdsds");
        jPanel1.add(errorPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        errorFechaIngreso.setText("sdsdsds");
        jPanel1.add(errorFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        errorHoraIngreso.setText("sdsdsds");
        jPanel1.add(errorHoraIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        errorTelefono.setText("sdsdsd");
        jPanel1.add(errorTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        errorPiso.setText("dsdsdsd");
        jPanel1.add(errorPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        errorBloque.setText("sddsd");
        jPanel1.add(errorBloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));
        jPanel1.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Iconos/Icon_Moto.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Iconos/Icon_Auto.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jLabel10.setText("JAMD");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MenuOptions regresar = new MenuOptions();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        String []info = new String[13];
        info[0]=txtPlaca.getText();
        if(radBtnAuto.isSelected()){
            info[1]="Auto";
        }else{
            if(radBtnMoto.isSelected()){
                info[1]="Moto";
            }
        }
        info[2]=txtName.getText();
        info[3]=txtTelefono.getText();        
        info[4]=spnPisos.getValue().toString();
        info[5]=spnBloques.getValue().toString();
        
        info[6]=txtName.getText();
        info[7]=txtName.getText();
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        
    }//GEN-LAST:event_txtNameActionPerformed

    private void radBtnAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBtnAutoActionPerformed

    private void radBtnMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnMotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBtnMotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Group_RadBtn;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel errorBloque;
    private javax.swing.JLabel errorFechaIngreso;
    private javax.swing.JLabel errorHoraIngreso;
    private javax.swing.JLabel errorNombre;
    private javax.swing.JLabel errorPiso;
    private javax.swing.JLabel errorPlaca;
    private javax.swing.JLabel errorTelefono;
    private javax.swing.JLabel errorTipo;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JRadioButton radBtnAuto;
    private javax.swing.JRadioButton radBtnMoto;
    private javax.swing.JSpinner spnBloques;
    private javax.swing.JSpinner spnPisos;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
