
package view;


public class Add_User extends javax.swing.JInternalFrame {

    /**
     * Creates new form Add_User
     */
    public Add_User() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        spinnerEdad = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        radioFeme = new javax.swing.JRadioButton();
        radioMascu = new javax.swing.JRadioButton();
        txtVaCelular = new javax.swing.JLabel();
        txtVaNombre = new javax.swing.JLabel();
        txtVaApellidos = new javax.swing.JLabel();
        txtVaDireccion = new javax.swing.JLabel();
        txtVaCedula = new javax.swing.JLabel();
        errGenero = new javax.swing.JLabel();
        errName = new javax.swing.JLabel();
        errLastName = new javax.swing.JLabel();
        errDireccion = new javax.swing.JLabel();
        errDni = new javax.swing.JLabel();
        errTelefono = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        radioMatu = new javax.swing.JRadioButton();
        radioVespe = new javax.swing.JRadioButton();
        Suplementos = new javax.swing.JPanel();
        checkCrea = new javax.swing.JCheckBox();
        checkProte = new javax.swing.JCheckBox();
        checkPre = new javax.swing.JCheckBox();
        checkL_Arg = new javax.swing.JCheckBox();
        checkL_Citru = new javax.swing.JCheckBox();
        checkQuemador = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        comboPago = new javax.swing.JComboBox<>();
        errHorario = new javax.swing.JLabel();
        errTipo = new javax.swing.JLabel();
        errPago1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        jLabel17.setText("jLabel11");

        setBackground(new java.awt.Color(0, 102, 102));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("AGREGAR NUEVO USUARIO");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL CLIENTE:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombres:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 27, -1, -1));

        jLabel2.setText("Apellidos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        jLabel3.setText("Dirección:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jLabel4.setText("C.I:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 27, 50, 20));

        jLabel5.setText("Telefono:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 80, 50, 20));

        jLabel6.setText("Edad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 50, 20));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 24, 186, -1));

        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 186, -1));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 186, -1));
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 24, 186, -1));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 186, 20));

        spinnerEdad.setModel(new javax.swing.SpinnerNumberModel(14, 14, 75, 1));
        jPanel1.add(spinnerEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 91, -1));

        jLabel7.setText("Genero:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 26, -1, 50));

        buttonGroup1.add(radioFeme);
        radioFeme.setText("Femenino");
        jPanel1.add(radioFeme, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 25, -1, -1));

        buttonGroup1.add(radioMascu);
        radioMascu.setText("Masculino");
        jPanel1.add(radioMascu, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 59, -1, -1));

        txtVaCelular.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtVaCelular.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(txtVaCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 170, -1));

        txtVaNombre.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtVaNombre.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(txtVaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 180, -1));

        txtVaApellidos.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtVaApellidos.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(txtVaApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 180, -1));

        txtVaDireccion.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtVaDireccion.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(txtVaDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 180, -1));

        txtVaCedula.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtVaCedula.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(txtVaCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 170, -1));

        errGenero.setText("errGenero");
        jPanel1.add(errGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 110, 20));

        errName.setText("errName");
        jPanel1.add(errName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 180, -1));

        errLastName.setText("errLastName");
        jPanel1.add(errLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 106, 180, 20));

        errDireccion.setText("errDireccion");
        jPanel1.add(errDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 180, 20));

        errDni.setText("errDni");
        jPanel1.add(errDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 180, 20));

        errTelefono.setText("errTelefono");
        jPanel1.add(errTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 180, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS MEMBRESÍA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Diaria", "Semanal", "Mensual", " " }));
        jPanel2.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel9.setText("Tipo:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel8.setText("Horario:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        buttonGroup2.add(radioMatu);
        radioMatu.setText("Matutino");
        jPanel2.add(radioMatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        buttonGroup2.add(radioVespe);
        radioVespe.setText("Vespertino");
        jPanel2.add(radioVespe, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        Suplementos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suplementos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        checkCrea.setText("Creatina");

        checkProte.setText("Proteína");

        checkPre.setText("Pre-Entreno");

        checkL_Arg.setText("L-Arginina");

        checkL_Citru.setText("L-Citrulina");

        checkQuemador.setText("Quemador");

        javax.swing.GroupLayout SuplementosLayout = new javax.swing.GroupLayout(Suplementos);
        Suplementos.setLayout(SuplementosLayout);
        SuplementosLayout.setHorizontalGroup(
            SuplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuplementosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(SuplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkL_Arg)
                    .addComponent(checkCrea))
                .addGap(28, 28, 28)
                .addGroup(SuplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkProte)
                    .addComponent(checkL_Citru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(SuplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkPre)
                    .addComponent(checkQuemador))
                .addContainerGap())
        );
        SuplementosLayout.setVerticalGroup(
            SuplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuplementosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(SuplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkCrea)
                    .addComponent(checkProte)
                    .addComponent(checkPre))
                .addGap(18, 18, 18)
                .addGroup(SuplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkL_Arg)
                    .addComponent(checkL_Citru)
                    .addComponent(checkQuemador))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.add(Suplementos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 350, 110));

        jLabel10.setText("Forma de Pago:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        comboPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Efectivo", "Transferencia", "Card" }));
        jPanel2.add(comboPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 120, -1));

        errHorario.setText("errHorario");
        jPanel2.add(errHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 120, 40));

        errTipo.setText("errTipo");
        jPanel2.add(errTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 130, 20));

        errPago1.setText("errPago");
        jPanel2.add(errPago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 110, -1));

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Suplementos;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JCheckBox checkCrea;
    public javax.swing.JCheckBox checkL_Arg;
    public javax.swing.JCheckBox checkL_Citru;
    public javax.swing.JCheckBox checkPre;
    public javax.swing.JCheckBox checkProte;
    public javax.swing.JCheckBox checkQuemador;
    public javax.swing.JComboBox<String> comboPago;
    public javax.swing.JComboBox<String> comboTipo;
    public javax.swing.JLabel errDireccion;
    public javax.swing.JLabel errDni;
    public javax.swing.JLabel errGenero;
    public javax.swing.JLabel errHorario;
    public javax.swing.JLabel errLastName;
    public javax.swing.JLabel errName;
    public javax.swing.JLabel errPago1;
    public javax.swing.JLabel errTelefono;
    public javax.swing.JLabel errTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JRadioButton radioFeme;
    public javax.swing.JRadioButton radioMascu;
    public javax.swing.JRadioButton radioMatu;
    public javax.swing.JRadioButton radioVespe;
    public javax.swing.JSpinner spinnerEdad;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtTelefono;
    public javax.swing.JLabel txtVaApellidos;
    public javax.swing.JLabel txtVaCedula;
    public javax.swing.JLabel txtVaCelular;
    public javax.swing.JLabel txtVaDireccion;
    public javax.swing.JLabel txtVaNombre;
    // End of variables declaration//GEN-END:variables
}
